import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import ViewportHeightSync from "@/components/ViewportHeightSync";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  // Permet à l'app d'occuper tout l'écran sous l'encoche ; les barres fixes
  // compensent ensuite avec les utilitaires pb-safe / pt-safe.
  viewportFit: "cover",
  themeColor: "#0a0a0f",
  // À l'ouverture du clavier, on veut que la MISE EN PAGE se réduise
  // (au lieu que le navigateur fasse défiler la page vers le haut, ce qui
  // faisait sortir l'en-tête et la question de l'écran).
  // Chrome/Android gère nativement ; iOS est traité par <ViewportHeightSync/>.
  interactiveWidget: "resizes-content",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#0a0a0f] text-gray-100`}
      >
        <ViewportHeightSync />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
